[package]
name = "matrix-parallel"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"
rayon = "1.10.0"

[lib]
name = "parallel"
path = "src/lib.rs"

[[bin]]
name = "matrix-parallel"
path = "src/main.rs"